export const
    XHR_ERROR = "XHR_ERROR",
    LOG_OUT = "LOG_OUT",
    SELECT_SCHOOL = "SELECT_SCHOOL",
    REVERT_CHANGES = "REVERT_CHANGES",
    TOGGLE_EDIT = "TOGGLE_EDIT",
    SAVE_CHANGES = "SAVE_CHANGES",
    SUBMIT_DELETE = "SUBMIT_DELETE",
    GENERATE_GROUPS = "GENERATE_GROUPS",

    SUBMIT_PATCH = "SUBMIT_PATCH",
    ADD_UNSAVED_ITEMS = "ADD_UNSAVED_ITEMS",

    AUTHORIZE = "AUTHORIZE",
    AUTHORIZE_SUCCESS = "AUTHORIZE_SUCCESS",
    AUTHORIZE_ERROR = "AUTHORIZE_ERROR",

    POST_ITEMS = "POST_ITEM",
    POST_ITEM_SUCCESS = "ITEM_POSTED",
    POST_ITEM_ERROR = "POST_ITEM_ERROR",

    GET_ITEMS = "GET_ITEMS",
    GET_ITEMS_SUCCESS = "RECEIVE_ITEMS",
    GET_ITEMS_ERROR = "GET_ITEMS_ERROR",

    PATCH_ITEM = "PATCH_ITEM",
    PATCH_ITEM_SUCCESS = "PATCH_ITEM_SUCCESS",
    PATCH_ITEM_ERROR = "PATCH_ITEM_ERROR",

    DELETE_ITEM = "DELETE_ITEM",
    DELETE_ITEM_SUCCESS = "ITEM_DELETED",
    DELETE_ITEM_ERROR = "DELETE_ITEM_ERROR",

    PARSE_SPREADSHEET = "PARSE_SPREADSHEET",
    PARSE_SPREADSHEET_SUCCESS = "SPREADSHEET_PARSED",
    PARSE_SPREADSHEET_ERROR = "SPREADSHEET_PARSE_ERROR";
