export const
    POST_STUDENTS = "POST_STUDENTS",
    POST_STUDENTS_SUCCESS = "STUDENTS_POSTED",
    POST_STUDENTS_ERROR = "POST_STUDENTS_ERROR",

    GET_STUDENTS = "GET_STUDENTS",
    GET_STUDENTS_SUCCESS = "RECEIVE_STUDENTS",
    GET_STUDENTS_ERROR = "GET_STUDENTS_ERROR",

    PUT_STUDENT = "UPDATE_STUDENT",
    PUT_STUDENT_SUCCESS  = "STUDENT_UPDATED",
    PUT_STUDENT_ERROR = "UPDATE_STUDENT_ERROR",

    PATCH_STUDENT = "PATCH_STUDENT",
    PATCH_STUDENT_SUCCESS = "PATCH_STUDENT_SUCCESS",
    PATCH_STUDENT_ERROR = "PATCH_STUDENT_ERROR",

    DELETE_STUDENTS = "DELETE_STUDENTS",
    DELETE_STUDENTS_SUCCESS = "STUDENTS_DELETED",
    DELETE_STUDENTS_ERROR = "DELETE_STUDENTS_ERROR",

    PARSE_SPREADSHEET = "PARSE_SPREADSHEET",
    PARSE_SPREADSHEET_SUCCESS = "SPREADSHEET_PARSED",
    PARSE_SPREADSHEET_ERROR = "SPREADSHEET_PARSE_ERROR";
